CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
                                                       "ProductVersion" character varying(32) NOT NULL,
                                                       CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE asp_net_roles (
                               id text NOT NULL,
                               name character varying(256),
                               normalized_name character varying(256),
                               concurrency_stamp text,
                               CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE asp_net_users (
                               id text NOT NULL,
                               first_name character varying(500),
                               last_name character varying(500),
                               is_deleted boolean NOT NULL,
                               gender character varying(60) NOT NULL,
                               description character varying(8000),
                               date_of_birth timestamp without time zone,
                               created_at timestamp without time zone NOT NULL,
                               updated_at timestamp without time zone,
                               created_by character varying(256) NOT NULL,
                               updated_by character varying(256),
                               user_name character varying(256),
                               normalized_user_name character varying(256),
                               email character varying(256),
                               normalized_email character varying(256),
                               email_confirmed boolean NOT NULL,
                               password_hash text,
                               security_stamp text,
                               concurrency_stamp text,
                               phone_number text,
                               phone_number_confirmed boolean NOT NULL,
                               two_factor_enabled boolean NOT NULL,
                               lockout_end timestamp with time zone,
                               lockout_enabled boolean NOT NULL,
                               access_failed_count integer NOT NULL,
                               CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE country (
                         id character varying(8000) NOT NULL,
                         name character varying(500) NOT NULL,
                         abbreviation character varying(6) NOT NULL,
                         created_by character varying(256) NOT NULL,
                         updated_by character varying(256),
                         created_at timestamp without time zone NOT NULL,
                         updated_at timestamp without time zone,
                         CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE data_protection_keys (
                                      id integer GENERATED BY DEFAULT AS IDENTITY,
                                      friendly_name text,
                                      xml text,
                                      CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
);

CREATE TABLE file_item_type (
                                id character varying(8000) NOT NULL,
                                name text NOT NULL,
                                created_by character varying(256) NOT NULL,
                                updated_by character varying(256),
                                created_at timestamp without time zone NOT NULL,
                                updated_at timestamp without time zone,
                                CONSTRAINT pk_file_item_type PRIMARY KEY (id)
);

CREATE TABLE logs (
                      id character varying(8000) NOT NULL,
                      application character varying(8000) NOT NULL,
                      logged character varying(8000) NOT NULL,
                      level character varying(8000) NOT NULL,
                      message character varying(8000) NOT NULL,
                      logger character varying(8000) NOT NULL,
                      callsite character varying(8000) NOT NULL,
                      exception character varying(8000) NOT NULL,
                      guid character varying(8000) NOT NULL,
                      created_by character varying(256) NOT NULL,
                      updated_by character varying(256),
                      created_at timestamp without time zone NOT NULL,
                      updated_at timestamp without time zone,
                      CONSTRAINT pk_logs PRIMARY KEY (id)
);

CREATE TABLE module_service (
                                id character varying(8000) NOT NULL,
                                name character varying(600) NOT NULL,
                                icon character varying(255) NOT NULL,
                                description character varying(8000),
                                created_by character varying(256) NOT NULL,
                                updated_by character varying(256),
                                created_at timestamp without time zone NOT NULL,
                                updated_at timestamp without time zone,
                                CONSTRAINT pk_module_service PRIMARY KEY (id)
);

CREATE TABLE permission (
                            id character varying(8000) NOT NULL,
                            name character varying(256) NOT NULL,
                            created_by character varying(256) NOT NULL,
                            updated_by character varying(256),
                            created_at timestamp without time zone NOT NULL,
                            updated_at timestamp without time zone,
                            CONSTRAINT pk_permission PRIMARY KEY (id)
);

CREATE TABLE asp_net_role_claims (
                                     id integer GENERATED BY DEFAULT AS IDENTITY,
                                     role_id text NOT NULL,
                                     claim_type text,
                                     claim_value text,
                                     CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
                                     CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_claims (
                                     id integer GENERATED BY DEFAULT AS IDENTITY,
                                     user_id text NOT NULL,
                                     claim_type text,
                                     claim_value text,
                                     CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
                                     CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_logins (
                                     login_provider text NOT NULL,
                                     provider_key text NOT NULL,
                                     provider_display_name text,
                                     user_id text NOT NULL,
                                     CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
                                     CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_roles (
                                    user_id text NOT NULL,
                                    role_id text NOT NULL,
                                    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
                                    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE,
                                    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_tokens (
                                     user_id text NOT NULL,
                                     login_provider text NOT NULL,
                                     name text NOT NULL,
                                     value text,
                                     CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
                                     CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE state (
                       id character varying(8000) NOT NULL,
                       name character varying(600) NOT NULL,
                       abbreviation character varying(6) NOT NULL,
                       country_id character varying(8000) NOT NULL,
                       created_by character varying(256) NOT NULL,
                       updated_by character varying(256),
                       created_at timestamp without time zone NOT NULL,
                       updated_at timestamp without time zone,
                       CONSTRAINT pk_state PRIMARY KEY (id),
                       CONSTRAINT fk_state_country_country_id FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE
);

CREATE TABLE file_item (
                           id character varying(8000) NOT NULL,
                           file_name character varying(8000) NOT NULL,
                           file_origin_name character varying(8000) NOT NULL,
                           file_extension character varying(6) NOT NULL,
                           href character varying(8000) NOT NULL,
                           alt_text character varying(8000),
                           file_item_type_id character varying(8000) NOT NULL,
                           created_by character varying(256) NOT NULL,
                           updated_by character varying(256),
                           created_at timestamp without time zone NOT NULL,
                           updated_at timestamp without time zone,
                           CONSTRAINT pk_file_item PRIMARY KEY (id),
                           CONSTRAINT fk_file_item_file_item_type_file_item_type_id FOREIGN KEY (file_item_type_id) REFERENCES file_item_type (id) ON DELETE CASCADE
);

CREATE TABLE district (
                          id character varying(8000) NOT NULL,
                          name character varying(600) NOT NULL,
                          abbreviation character varying(6) NOT NULL,
                          state_id character varying(8000) NOT NULL,
                          created_by character varying(256) NOT NULL,
                          updated_by character varying(256),
                          created_at timestamp without time zone NOT NULL,
                          updated_at timestamp without time zone,
                          CONSTRAINT pk_district PRIMARY KEY (id),
                          CONSTRAINT fk_district_state_state_id FOREIGN KEY (state_id) REFERENCES state (id) ON DELETE CASCADE
);

CREATE TABLE user_file_item (
                                id character varying(8000) NOT NULL,
                                file_item_id character varying(8000) NOT NULL,
                                application_user_id character varying(8000) NOT NULL,
                                is_avatar boolean NOT NULL,
                                order_nr integer,
                                created_by character varying(256) NOT NULL,
                                updated_by character varying(256),
                                created_at timestamp without time zone NOT NULL,
                                updated_at timestamp without time zone,
                                CONSTRAINT pk_user_file_item PRIMARY KEY (id),
                                CONSTRAINT fk_user_file_item_asp_net_users_application_user_id FOREIGN KEY (application_user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE,
                                CONSTRAINT fk_user_file_item_file_item_file_item_id FOREIGN KEY (file_item_id) REFERENCES file_item (id) ON DELETE CASCADE
);

CREATE TABLE organisation (
                              id character varying(8000) NOT NULL,
                              name character varying(1000) NOT NULL,
                              zip character varying(12) NOT NULL,
                              district_id character varying(8000) NOT NULL,
                              description character varying(8000),
                              latitude double precision,
                              longitude double precision,
                              color character varying(7),
                              created_by character varying(256) NOT NULL,
                              updated_by character varying(256),
                              created_at timestamp without time zone NOT NULL,
                              updated_at timestamp without time zone,
                              CONSTRAINT pk_organisation PRIMARY KEY (id),
                              CONSTRAINT fk_organisation_district_district_id FOREIGN KEY (district_id) REFERENCES district (id) ON DELETE CASCADE
);

CREATE TABLE organisation_file_item (
                                        id character varying(8000) NOT NULL,
                                        file_item_id character varying(8000) NOT NULL,
                                        organisation_id character varying(8000) NOT NULL,
                                        is_logo boolean NOT NULL,
                                        order_nr integer,
                                        created_by character varying(256) NOT NULL,
                                        updated_by character varying(256),
                                        created_at timestamp without time zone NOT NULL,
                                        updated_at timestamp without time zone,
                                        CONSTRAINT pk_organisation_file_item PRIMARY KEY (id),
                                        CONSTRAINT fk_organisation_file_item_file_item_file_item_id FOREIGN KEY (file_item_id) REFERENCES file_item (id) ON DELETE CASCADE,
                                        CONSTRAINT fk_organisation_file_item_organisation_organisation_id FOREIGN KEY (organisation_id) REFERENCES organisation (id) ON DELETE CASCADE
);

CREATE TABLE organisation_module_service (
                                             id character varying(8000) NOT NULL,
                                             module_service_id character varying(8000) NOT NULL,
                                             organisation_id character varying(8000) NOT NULL,
                                             is_active boolean NOT NULL,
                                             created_by character varying(256) NOT NULL,
                                             updated_by character varying(256),
                                             created_at timestamp without time zone NOT NULL,
                                             updated_at timestamp without time zone,
                                             CONSTRAINT pk_organisation_module_service PRIMARY KEY (id),
                                             CONSTRAINT fk_organisation_module_service_module_service_module_service_id FOREIGN KEY (module_service_id) REFERENCES module_service (id) ON DELETE CASCADE,
                                             CONSTRAINT fk_organisation_module_service_organisation_organisation_id FOREIGN KEY (organisation_id) REFERENCES organisation (id) ON DELETE CASCADE
);

CREATE TABLE user_organisation (
                                   id character varying(8000) NOT NULL,
                                   application_user_id character varying(8000) NOT NULL,
                                   organisation_id character varying(8000) NOT NULL,
                                   is_primary boolean NOT NULL,
                                   created_by character varying(256) NOT NULL,
                                   updated_by character varying(256),
                                   created_at timestamp without time zone NOT NULL,
                                   updated_at timestamp without time zone,
                                   CONSTRAINT pk_user_organisation PRIMARY KEY (id),
                                   CONSTRAINT fk_user_organisation_asp_net_users_application_user_id FOREIGN KEY (application_user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE,
                                   CONSTRAINT fk_user_organisation_organisation_organisation_id FOREIGN KEY (organisation_id) REFERENCES organisation (id) ON DELETE CASCADE
);

CREATE TABLE user_organisation_permission (
                                              id character varying(8000) NOT NULL,
                                              user_organisation_id character varying(8000) NOT NULL,
                                              permission_id character varying(8000) NOT NULL,
                                              created_by character varying(256) NOT NULL,
                                              updated_by character varying(256),
                                              created_at timestamp without time zone NOT NULL,
                                              updated_at timestamp without time zone,
                                              CONSTRAINT pk_user_organisation_permission PRIMARY KEY (id),
                                              CONSTRAINT fk_user_organisation_permission_permission_permission_id FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE,
                                              CONSTRAINT "fk_user_organisation_permission_user_organisation_user_organis~" FOREIGN KEY (user_organisation_id) REFERENCES user_organisation (id) ON DELETE CASCADE
);

CREATE INDEX "IX_asp_net_role_claims_role_id" ON asp_net_role_claims (role_id);

CREATE UNIQUE INDEX "IX_asp_net_roles_normalized_name" ON asp_net_roles (normalized_name);

CREATE INDEX "IX_asp_net_user_claims_user_id" ON asp_net_user_claims (user_id);

CREATE INDEX "IX_asp_net_user_logins_user_id" ON asp_net_user_logins (user_id);

CREATE INDEX "IX_asp_net_user_roles_role_id" ON asp_net_user_roles (role_id);

CREATE INDEX "IX_asp_net_users_normalized_email" ON asp_net_users (normalized_email);

CREATE UNIQUE INDEX "IX_asp_net_users_normalized_user_name" ON asp_net_users (normalized_user_name);

CREATE UNIQUE INDEX "IX_country_abbreviation" ON country (abbreviation);

CREATE UNIQUE INDEX "IX_country_name" ON country (name);

CREATE INDEX "IX_district_state_id" ON district (state_id);

CREATE INDEX "IX_file_item_file_item_type_id" ON file_item (file_item_type_id);

CREATE UNIQUE INDEX "IX_file_item_file_name" ON file_item (file_name);

CREATE UNIQUE INDEX "IX_file_item_href" ON file_item (href);

CREATE UNIQUE INDEX "IX_file_item_type_name" ON file_item_type (name);

CREATE UNIQUE INDEX "IX_module_service_name" ON module_service (name);

CREATE INDEX "IX_organisation_district_id" ON organisation (district_id);

CREATE UNIQUE INDEX "IX_organisation_name" ON organisation (name);

CREATE INDEX "IX_organisation_file_item_file_item_id" ON organisation_file_item (file_item_id);

CREATE INDEX "IX_organisation_file_item_organisation_id" ON organisation_file_item (organisation_id);

CREATE INDEX "IX_organisation_module_service_module_service_id" ON organisation_module_service (module_service_id);

CREATE INDEX "IX_organisation_module_service_organisation_id" ON organisation_module_service (organisation_id);

CREATE UNIQUE INDEX "IX_permission_name" ON permission (name);

CREATE INDEX "IX_state_country_id" ON state (country_id);

CREATE INDEX "IX_user_file_item_application_user_id" ON user_file_item (application_user_id);

CREATE INDEX "IX_user_file_item_file_item_id" ON user_file_item (file_item_id);

CREATE INDEX "IX_user_organisation_application_user_id" ON user_organisation (application_user_id);

CREATE INDEX "IX_user_organisation_organisation_id" ON user_organisation (organisation_id);

CREATE INDEX "IX_user_organisation_permission_permission_id" ON user_organisation_permission (permission_id);

CREATE INDEX "IX_user_organisation_permission_user_organisation_id" ON user_organisation_permission (user_organisation_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240609071744_Init', '8.0.4');

COMMIT;

